# Generated by Django 4.1.2 on 2025-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description_book_isbn_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
